name: Release Please

on:
  push:
    branches:
      - master

permissions:
  contents: write # To update version files and create releases
  pull-requests: write # To create and manage release PRs
  issues: write # For label management

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: python
          package-name: safesmith
          version-file: "src/safesmith/version.py"
          changelog-types: |
            [
              {"type":"feat","section":"Features","hidden":false},
              {"type":"fix","section":"Bug Fixes","hidden":false},
              {"type":"docs","section":"Documentation","hidden":false},
              {"type":"chore","section":"Miscellaneous","hidden":true}
            ]

      # The following steps run only if a new release was created
      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}

      - name: Set up Python
        uses: actions/setup-python@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          python-version: "3.10"

      - name: Install hatch
        if: ${{ steps.release.outputs.release_created }}
        run: |
          python -m pip install --upgrade pip
          pip install hatch

      - name: Build and publish
        if: ${{ steps.release.outputs.release_created }}
        env:
          HATCH_INDEX_AUTH: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          hatch build
          hatch publish --user=__token__
